


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."booking_status" AS ENUM (
    'pending',
    'confirmed',
    'cancelled'
);


ALTER TYPE "public"."booking_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."assign_confirmation_number"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $_$
DECLARE
  target_date date;
  date_str text;
  next_seq int;
BEGIN
  IF NEW.confirmation_number IS NOT NULL THEN
    RETURN NEW;
  END IF;

  target_date := (COALESCE(NEW.created_at, now()) AT TIME ZONE 'Asia/Manila')::date;
  date_str := to_char(target_date, 'YYYYMMDD');

  -- Serializes concurrent inserts on the same day so two simultaneous
  -- bookings can't compute the same next sequence number.
  PERFORM pg_advisory_xact_lock(hashtext(date_str));

  SELECT COALESCE(MAX(substring(confirmation_number FROM '-(\d+)$')::int), 0) + 1
  INTO next_seq
  FROM transactions
  WHERE confirmation_number LIKE 'MP2H-' || date_str || '-%';

  NEW.confirmation_number := 'MP2H-' || date_str || '-' || lpad(next_seq::text, 3, '0');
  RETURN NEW;
END;
$_$;


ALTER FUNCTION "public"."assign_confirmation_number"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."enforce_booking_blacklist"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  if public.is_blacklisted(new.player_email, new.player_phone) then
    raise exception 'This email or phone number is not able to book at this time. Please contact us for assistance.';
  end if;
  return new;
end;
$$;


ALTER FUNCTION "public"."enforce_booking_blacklist"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_blacklisted"("check_email" "text", "check_phone" "text") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  return exists (
    select 1 from public.blacklist
    where (email is not null and check_email is not null and lower(trim(email)) = lower(trim(check_email)))
       or (phone is not null and check_phone is not null and regexp_replace(phone, '\D', '', 'g') = regexp_replace(check_phone, '\D', '', 'g'))
  );
end;
$$;


ALTER FUNCTION "public"."is_blacklisted"("check_email" "text", "check_phone" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."reset_transactions_sequence"() RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('transactions', 'id'), 1, false);
END;
$$;


ALTER FUNCTION "public"."reset_transactions_sequence"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."addons" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "price" numeric DEFAULT 0 NOT NULL,
    "max_quantity" integer DEFAULT 1 NOT NULL,
    "active" boolean DEFAULT true NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."addons" OWNER TO "postgres";


ALTER TABLE "public"."addons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."addons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."blacklist" (
    "id" bigint NOT NULL,
    "email" "text",
    "phone" "text",
    "reason" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "blacklist_email_or_phone" CHECK ((("email" IS NOT NULL) OR ("phone" IS NOT NULL)))
);


ALTER TABLE "public"."blacklist" OWNER TO "postgres";


ALTER TABLE "public"."blacklist" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."blacklist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."blocked_slots" (
    "id" bigint NOT NULL,
    "court_id" "uuid" NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "reason" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."blocked_slots" OWNER TO "postgres";


ALTER TABLE "public"."blocked_slots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."blocked_slots_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."booking_addons" (
    "id" bigint NOT NULL,
    "transaction_id" bigint NOT NULL,
    "addon_id" bigint,
    "name_snapshot" "text" NOT NULL,
    "price_snapshot" numeric NOT NULL,
    "quantity" integer DEFAULT 1 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."booking_addons" OWNER TO "postgres";


ALTER TABLE "public"."booking_addons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."booking_addons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "court_id" "uuid",
    "player_name" "text" NOT NULL,
    "player_phone" "text" NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "status" "public"."booking_status" DEFAULT 'pending'::"public"."booking_status",
    "receipt_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "price" numeric,
    "player_email" "text",
    "transaction_id" bigint,
    "checked_in" boolean DEFAULT false NOT NULL,
    "checked_in_at" timestamp with time zone,
    "reschedule_reason" "text",
    "daily_sequence" integer,
    "admin_remark" "text",
    "reminder_1_sent_at" timestamp with time zone,
    "reminder_2_sent_at" timestamp with time zone
);


ALTER TABLE "public"."bookings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."courts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "image_url" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "show_when_disabled" boolean DEFAULT false NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."courts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."email_settings" (
    "id" smallint DEFAULT 1 NOT NULL,
    "gmail_user" "text",
    "gmail_app_password" "text",
    "admin_notification_email" "text",
    "app_password_set" boolean DEFAULT false NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "cron_secret" "text",
    "cron_secret_set" boolean DEFAULT false NOT NULL,
    CONSTRAINT "email_settings_singleton" CHECK (("id" = 1))
);


ALTER TABLE "public"."email_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."holidays" (
    "id" bigint NOT NULL,
    "holiday_date" "date" NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."holidays" OWNER TO "postgres";


ALTER TABLE "public"."holidays" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."holidays_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."landing_photos" (
    "id" bigint NOT NULL,
    "image_url" "text" NOT NULL,
    "caption" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."landing_photos" OWNER TO "postgres";


ALTER TABLE "public"."landing_photos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."landing_photos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."payment_qr_codes" (
    "id" bigint NOT NULL,
    "label" "text" NOT NULL,
    "image_url" "text" NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."payment_qr_codes" OWNER TO "postgres";


ALTER TABLE "public"."payment_qr_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."payment_qr_codes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."price_tiers" (
    "id" bigint NOT NULL,
    "start_hour" integer NOT NULL,
    "end_hour" integer NOT NULL,
    "price" numeric NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "price_tiers_hours_check" CHECK ((("start_hour" >= 0) AND ("start_hour" < 24) AND ("end_hour" > "start_hour") AND ("end_hour" <= 24)))
);


ALTER TABLE "public"."price_tiers" OWNER TO "postgres";


ALTER TABLE "public"."price_tiers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."price_tiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."site_settings" (
    "id" integer DEFAULT 1 NOT NULL,
    "site_title" "text" DEFAULT 'MP2H Pickleball'::"text" NOT NULL,
    "site_subtitle" "text" DEFAULT 'Book a court online — quick, easy, and no phone calls needed.'::"text" NOT NULL,
    "logo_url" "text",
    "primary_color" "text" DEFAULT '#059669'::"text" NOT NULL,
    "submit_button_label" "text" DEFAULT 'Submit Booking'::"text" NOT NULL,
    "gcash_qr_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "payment_note" "text",
    "opening_hour" integer DEFAULT 6 NOT NULL,
    "closing_hour" integer DEFAULT 22 NOT NULL,
    "open_days" integer[] DEFAULT '{0,1,2,3,4,5,6}'::integer[] NOT NULL,
    "pending_hold_minutes" integer DEFAULT 10 NOT NULL,
    "allow_multi_slot_booking" boolean DEFAULT false NOT NULL,
    "show_price" boolean DEFAULT false NOT NULL,
    "pricing_mode" "text" DEFAULT 'flat'::"text" NOT NULL,
    "flat_price" numeric DEFAULT 0 NOT NULL,
    "notify_customer_on_approval" boolean DEFAULT false NOT NULL,
    "auto_confirm_bookings" boolean DEFAULT false NOT NULL,
    "attach_marketing_image" boolean DEFAULT false NOT NULL,
    "marketing_image_url" "text",
    "customer_email_footer_html" "text",
    "attach_receipt_to_customer_email" boolean DEFAULT false NOT NULL,
    "selection_color" "text" DEFAULT '#059669'::"text" NOT NULL,
    "button_bg_color" "text" DEFAULT '#059669'::"text" NOT NULL,
    "button_label_color" "text" DEFAULT '#ffffff'::"text" NOT NULL,
    "admin_tab_font_color" "text" DEFAULT '#475569'::"text" NOT NULL,
    "admin_tab_active_bg_color" "text" DEFAULT '#059669'::"text" NOT NULL,
    "landing_tagline" "text",
    "landing_about_html" "text",
    "landing_policy_html" "text",
    "landing_address" "text",
    "landing_contact_phone" "text",
    "landing_contact_email" "text",
    "landing_facebook_url" "text",
    "landing_instagram_url" "text",
    "landing_google_maps_url" "text",
    "landing_facebook_page_id" "text",
    "landing_enable_fb_chat" boolean DEFAULT false NOT NULL,
    "landing_show_gallery" boolean DEFAULT true NOT NULL,
    "landing_tiktok_url" "text",
    "landing_youtube_url" "text",
    "landing_twitter_url" "text",
    "landing_whatsapp_number" "text",
    "logo_height" integer DEFAULT 48 NOT NULL,
    "booking_hold_warning_text" "text",
    "checkout_hold_minutes" integer DEFAULT 15 NOT NULL,
    "availability_refresh_seconds" integer DEFAULT 60 NOT NULL,
    "booking_reminder_1_enabled" boolean DEFAULT false NOT NULL,
    "booking_reminder_1_hours" integer DEFAULT 24 NOT NULL,
    "booking_reminder_2_enabled" boolean DEFAULT false NOT NULL,
    "booking_reminder_2_hours" integer DEFAULT 4 NOT NULL,
    CONSTRAINT "site_settings_hours_check" CHECK ((("opening_hour" >= 0) AND ("opening_hour" < 24) AND ("closing_hour" > "opening_hour") AND ("closing_hour" <= 24))),
    CONSTRAINT "site_settings_pending_hold_check" CHECK (("pending_hold_minutes" > 0)),
    CONSTRAINT "site_settings_pricing_mode_check" CHECK (("pricing_mode" = ANY (ARRAY['flat'::"text", 'tiered'::"text"]))),
    CONSTRAINT "site_settings_single_row" CHECK (("id" = 1))
);


ALTER TABLE "public"."site_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."slot_holds" (
    "id" bigint NOT NULL,
    "court_id" "uuid" NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."slot_holds" OWNER TO "postgres";


ALTER TABLE "public"."slot_holds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."slot_holds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "confirmation_number" "text"
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


ALTER TABLE "public"."transactions" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."addons"
    ADD CONSTRAINT "addons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blacklist"
    ADD CONSTRAINT "blacklist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blocked_slots"
    ADD CONSTRAINT "blocked_slots_court_id_start_time_key" UNIQUE ("court_id", "start_time");



ALTER TABLE ONLY "public"."blocked_slots"
    ADD CONSTRAINT "blocked_slots_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."booking_addons"
    ADD CONSTRAINT "booking_addons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."courts"
    ADD CONSTRAINT "courts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."email_settings"
    ADD CONSTRAINT "email_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."holidays"
    ADD CONSTRAINT "holidays_holiday_date_key" UNIQUE ("holiday_date");



ALTER TABLE ONLY "public"."holidays"
    ADD CONSTRAINT "holidays_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."landing_photos"
    ADD CONSTRAINT "landing_photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."payment_qr_codes"
    ADD CONSTRAINT "payment_qr_codes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."price_tiers"
    ADD CONSTRAINT "price_tiers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."site_settings"
    ADD CONSTRAINT "site_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."slot_holds"
    ADD CONSTRAINT "slot_holds_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



CREATE INDEX "booking_addons_transaction_idx" ON "public"."booking_addons" USING "btree" ("transaction_id");



CREATE UNIQUE INDEX "idx_transactions_confirmation_number" ON "public"."transactions" USING "btree" ("confirmation_number") WHERE ("confirmation_number" IS NOT NULL);



CREATE INDEX "slot_holds_court_start_idx" ON "public"."slot_holds" USING "btree" ("court_id", "start_time");



CREATE OR REPLACE TRIGGER "trg_assign_confirmation_number" BEFORE INSERT ON "public"."transactions" FOR EACH ROW EXECUTE FUNCTION "public"."assign_confirmation_number"();



CREATE OR REPLACE TRIGGER "trg_enforce_booking_blacklist" BEFORE INSERT ON "public"."bookings" FOR EACH ROW EXECUTE FUNCTION "public"."enforce_booking_blacklist"();



ALTER TABLE ONLY "public"."blocked_slots"
    ADD CONSTRAINT "blocked_slots_court_id_fkey" FOREIGN KEY ("court_id") REFERENCES "public"."courts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."booking_addons"
    ADD CONSTRAINT "booking_addons_addon_id_fkey" FOREIGN KEY ("addon_id") REFERENCES "public"."addons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."booking_addons"
    ADD CONSTRAINT "booking_addons_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_court_id_fkey" FOREIGN KEY ("court_id") REFERENCES "public"."courts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id");



ALTER TABLE ONLY "public"."slot_holds"
    ADD CONSTRAINT "slot_holds_court_id_fkey" FOREIGN KEY ("court_id") REFERENCES "public"."courts"("id") ON DELETE CASCADE;



CREATE POLICY "Anyone can create booking add-ons" ON "public"."booking_addons" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can create slot holds" ON "public"."slot_holds" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anyone can create transactions" ON "public"."transactions" FOR INSERT TO "authenticated", "anon" WITH CHECK (true);



CREATE POLICY "Anyone can delete slot holds" ON "public"."slot_holds" FOR DELETE USING (true);



CREATE POLICY "Anyone can view blocked slots" ON "public"."blocked_slots" FOR SELECT USING (true);



CREATE POLICY "Anyone can view courts" ON "public"."courts" FOR SELECT USING (true);



CREATE POLICY "Anyone can view holidays" ON "public"."holidays" FOR SELECT USING (true);



CREATE POLICY "Anyone can view landing photos" ON "public"."landing_photos" FOR SELECT USING (true);



CREATE POLICY "Anyone can view payment qr codes" ON "public"."payment_qr_codes" FOR SELECT USING (true);



CREATE POLICY "Anyone can view price tiers" ON "public"."price_tiers" FOR SELECT USING (true);



CREATE POLICY "Anyone can view site settings" ON "public"."site_settings" FOR SELECT USING (true);



CREATE POLICY "Anyone can view slot holds" ON "public"."slot_holds" FOR SELECT USING (true);



CREATE POLICY "Anyone can view transactions" ON "public"."transactions" FOR SELECT USING (true);



CREATE POLICY "Authenticated can delete booking add-ons" ON "public"."booking_addons" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated can delete bookings" ON "public"."bookings" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated can insert bookings" ON "public"."bookings" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated can insert transactions" ON "public"."transactions" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated can manage addons" ON "public"."addons" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated can update email settings" ON "public"."email_settings" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated can view all addons" ON "public"."addons" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Authenticated can view booking add-ons" ON "public"."booking_addons" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Authenticated can view email settings" ON "public"."email_settings" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete blocked slots" ON "public"."blocked_slots" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete courts" ON "public"."courts" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete holidays" ON "public"."holidays" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete landing photos" ON "public"."landing_photos" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete payment qr codes" ON "public"."payment_qr_codes" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can delete price tiers" ON "public"."price_tiers" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Authenticated users can insert blocked slots" ON "public"."blocked_slots" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert courts" ON "public"."courts" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert holidays" ON "public"."holidays" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert landing photos" ON "public"."landing_photos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert payment qr codes" ON "public"."payment_qr_codes" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert price tiers" ON "public"."price_tiers" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Authenticated users can insert site settings" ON "public"."site_settings" FOR INSERT TO "authenticated" WITH CHECK (("id" = 1));



CREATE POLICY "Authenticated users can manage blacklist" ON "public"."blacklist" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can update bookings" ON "public"."bookings" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can update courts" ON "public"."courts" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can update price tiers" ON "public"."price_tiers" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Authenticated users can update site settings" ON "public"."site_settings" FOR UPDATE TO "authenticated" USING (("id" = 1)) WITH CHECK (("id" = 1));



CREATE POLICY "Authenticated users can view blacklist" ON "public"."blacklist" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Public bookings view" ON "public"."bookings" FOR SELECT USING (true);



CREATE POLICY "Public can view active addons" ON "public"."addons" FOR SELECT TO "anon" USING (("active" = true));



CREATE POLICY "Public courts view" ON "public"."courts" FOR SELECT USING (true);



CREATE POLICY "Public insert booking" ON "public"."bookings" FOR INSERT WITH CHECK (true);



ALTER TABLE "public"."addons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blacklist" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blocked_slots" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."booking_addons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bookings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."courts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."email_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."holidays" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."landing_photos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."payment_qr_codes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."price_tiers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."site_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."slot_holds" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."bookings";












GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT ALL ON FUNCTION "public"."assign_confirmation_number"() TO "anon";
GRANT ALL ON FUNCTION "public"."assign_confirmation_number"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."assign_confirmation_number"() TO "service_role";



GRANT ALL ON FUNCTION "public"."enforce_booking_blacklist"() TO "anon";
GRANT ALL ON FUNCTION "public"."enforce_booking_blacklist"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."enforce_booking_blacklist"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_blacklisted"("check_email" "text", "check_phone" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."is_blacklisted"("check_email" "text", "check_phone" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_blacklisted"("check_email" "text", "check_phone" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."reset_transactions_sequence"() TO "anon";
GRANT ALL ON FUNCTION "public"."reset_transactions_sequence"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."reset_transactions_sequence"() TO "service_role";
























GRANT ALL ON TABLE "public"."addons" TO "anon";
GRANT ALL ON TABLE "public"."addons" TO "authenticated";
GRANT ALL ON TABLE "public"."addons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."blacklist" TO "anon";
GRANT ALL ON TABLE "public"."blacklist" TO "authenticated";
GRANT ALL ON TABLE "public"."blacklist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blacklist_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."blocked_slots" TO "anon";
GRANT ALL ON TABLE "public"."blocked_slots" TO "authenticated";
GRANT ALL ON TABLE "public"."blocked_slots" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blocked_slots_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blocked_slots_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blocked_slots_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."booking_addons" TO "anon";
GRANT ALL ON TABLE "public"."booking_addons" TO "authenticated";
GRANT ALL ON TABLE "public"."booking_addons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."booking_addons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."booking_addons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."booking_addons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON TABLE "public"."courts" TO "anon";
GRANT ALL ON TABLE "public"."courts" TO "authenticated";
GRANT ALL ON TABLE "public"."courts" TO "service_role";



GRANT ALL ON TABLE "public"."email_settings" TO "anon";
GRANT ALL ON TABLE "public"."email_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."email_settings" TO "service_role";



GRANT SELECT("id") ON TABLE "public"."email_settings" TO "authenticated";



GRANT SELECT("gmail_user"),UPDATE("gmail_user") ON TABLE "public"."email_settings" TO "authenticated";



GRANT UPDATE("gmail_app_password") ON TABLE "public"."email_settings" TO "authenticated";



GRANT SELECT("admin_notification_email"),UPDATE("admin_notification_email") ON TABLE "public"."email_settings" TO "authenticated";



GRANT SELECT("app_password_set"),UPDATE("app_password_set") ON TABLE "public"."email_settings" TO "authenticated";



GRANT SELECT("updated_at"),UPDATE("updated_at") ON TABLE "public"."email_settings" TO "authenticated";



GRANT SELECT("cron_secret") ON TABLE "public"."email_settings" TO "authenticated";



GRANT ALL ON TABLE "public"."holidays" TO "anon";
GRANT ALL ON TABLE "public"."holidays" TO "authenticated";
GRANT ALL ON TABLE "public"."holidays" TO "service_role";



GRANT ALL ON SEQUENCE "public"."holidays_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."holidays_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."holidays_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."landing_photos" TO "anon";
GRANT ALL ON TABLE "public"."landing_photos" TO "authenticated";
GRANT ALL ON TABLE "public"."landing_photos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."landing_photos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."landing_photos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."landing_photos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."payment_qr_codes" TO "anon";
GRANT ALL ON TABLE "public"."payment_qr_codes" TO "authenticated";
GRANT ALL ON TABLE "public"."payment_qr_codes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."payment_qr_codes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."payment_qr_codes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."payment_qr_codes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."price_tiers" TO "anon";
GRANT ALL ON TABLE "public"."price_tiers" TO "authenticated";
GRANT ALL ON TABLE "public"."price_tiers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."price_tiers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."price_tiers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."price_tiers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."site_settings" TO "anon";
GRANT ALL ON TABLE "public"."site_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."site_settings" TO "service_role";



GRANT ALL ON TABLE "public"."slot_holds" TO "anon";
GRANT ALL ON TABLE "public"."slot_holds" TO "authenticated";
GRANT ALL ON TABLE "public"."slot_holds" TO "service_role";



GRANT ALL ON SEQUENCE "public"."slot_holds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."slot_holds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."slot_holds_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT ALL ON TABLE "public"."transactions" TO "authenticated";
GRANT ALL ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































